var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/users/route.js")
R.c("server/chunks/[externals]_fs_5cc227fd._.js")
R.c("server/chunks/node_modules_next_91081101._.js")
R.c("server/chunks/node_modules_zod_v3_f358d7b3._.js")
R.c("server/chunks/node_modules_casbin_lib_esm_588bc42d._.js")
R.c("server/chunks/[root-of-the-server]__870b318f._.js")
R.c("server/chunks/[root-of-the-server]__2c597834._.js")
R.c("server/chunks/apps_web__next-internal_server_app_api_admin_users_route_actions_8838cf01.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/web/app/api/admin/users/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/web/app/api/admin/users/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
