var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/enroll-face/route.js")
R.c("server/chunks/[externals]_fs_8db4fd59._.js")
R.c("server/chunks/node_modules_next_70b64885._.js")
R.c("server/chunks/node_modules_zod_v3_f358d7b3._.js")
R.c("server/chunks/node_modules_casbin_lib_esm_588bc42d._.js")
R.c("server/chunks/[root-of-the-server]__ba609178._.js")
R.c("server/chunks/[root-of-the-server]__af5cdddd._.js")
R.c("server/chunks/apps_web__next-internal_server_app_api_auth_enroll-face_route_actions_357cf94e.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/web/app/api/auth/enroll-face/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/web/app/api/auth/enroll-face/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
