var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/roles/route.js")
R.c("server/chunks/[externals]_fs_98ea8d25._.js")
R.c("server/chunks/node_modules_next_ca8dee2b._.js")
R.c("server/chunks/node_modules_zod_v3_f358d7b3._.js")
R.c("server/chunks/node_modules_casbin_lib_esm_588bc42d._.js")
R.c("server/chunks/[root-of-the-server]__ba609178._.js")
R.c("server/chunks/[root-of-the-server]__ea0f8af8._.js")
R.c("server/chunks/apps_web__next-internal_server_app_api_admin_roles_route_actions_30bf4e0d.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/web/app/api/admin/roles/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/web/app/api/admin/roles/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
